# -*- coding: utf-8 -*-
"""Sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ep7pgg4diUZ_UAxFULq44fdDiIExLgti
"""



"""To display Hello World"""

print("Hello world")

# To print message-Im student

"""gjjhjgjgj
bbjhbjbjhbhkbkbk
jnbjbhb"""